### PR TITLE
[WIP]Add an option to animate to back position (BarChart).

### PR DESCRIPTION
**Pull request by fummicc1**
I want to keep the label in its final state after the bottom label of the graph has been dragged.

## Description, Motivation and Context

Like the following GIF, we cannot keep `BarChartView#touchLocation` after dragging label.
RPReplay_Final1603364812

It is not always a problem, but this featuer may not be flexible. I prefer to choose whether it keeps the `touchLocation` after dragging.

|My desired behavior|
|---|
|RPReplay_Final1603367132|

## How Has This Been Tested?

- ⌘ + U
- Run on real device in te following environment.
    - iOS 14
    - Xcode12.0.1
    - iPhone SE (2nd)

Please watch the result.
RPReplay_Final1603367132

## Screenshots (if appropriate):
|before|after|
|---|---|
|RPReplay_Final1603364812|RPReplay_Final1603367132|

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-functional change (Updating Documentation, CI automation, etc..)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by KGALLET** [comment]
Was it a choice from your side to leave the bar bigger than the other ones when you stop touching the bars ?

**Comment by fummicc1** [comment]
@KGALLET Yes it is, but I feel new function that can deselect bar after reading your comment.

**Comment by KGALLET** [comment]
I saw your last commit, what about doing it like that : 
```
   DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
    withAnimation(Animation.easeOut(duration: 1.2)) {
       self.showValue = false
       self.showLabelValue = false
       self.touchLocation = -1
    }
   }
  ``` ?
  
 It return to the initial position with animation and not in one time which is smoother imo

**Comment by fummicc1** [comment]
@KGALLET Thank you for your advice! I have applied it :) I am going to update this PR description because it is a little different from initial state.

**Comment by KGALLET** [comment]
No problem, I actually get inspired by your PR, to use in one of my app, that's why I ended up to use it :)

**Pull request merged**
