### PR TITLE
Created interaction for PieChart

### PR DESCRIPTION
**Pull request by Lebron1992**
@AppPear   Finished the issue opened on https://github.com/AppPear/ChartView/issues/97

Below is the interaction looks like:

pie-chart-interaction

### CODE REVIEW

**Comment by Lebron1992** [comment]
```
/Users/runner/work/ChartView/ChartView/Sources/SwiftUICharts/PieChart/PieChartRow.swift:46:38: error: reference to property 'currentTouchedIndex' in closure requires explicit 'self.' to make capture semantics explicit
                        .scaleEffect(currentTouchedIndex == i ? 1.1 : 1)
```

Xcode 14 doesn't require `self` in the View closure.

**Comment by AppPear** [comment]
Looks super good! I'll check the code soon and we can release this in the next beta in v2

**Comment by AppPear** [comment]
Also till v2 it can be released on v1 also

**Comment by Lebron1992** [comment]
> Looks super good! I'll check the code soon and we can release this in the next beta in v2

Ok! That sounds great.

**Pull request merged**
